# services:
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - "27007:27017"
#     volumes:
#       - ./mongodata:/data/db
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#       - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
#     restart: always

# networks:
#   backend:
#     driver: bridge
# volumes:
#   mongodata:




services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      # - "27007:27017"
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    # Remove authentication for local development
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

  pgvector:
    image: ankane/pgvector:latest
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
volumes:
  mongodata:
  pgvector_data: